services:
  - type: web
    name: vosapp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: VOS_USE_ENV_PROXY
        value: "0"